create table persons(
                       id integer not null generated by default as identity (start with 1, increment by 1),
                       name varchar(100) not null unique,
                       primary key (id)
);

create table actors(
                      id integer not null generated by default as identity (start with 1, increment by 1),
                      name varchar(100) not null unique,
                      actor_id integer not null references persons on delete restrict,
                      primary key (id)
);

create table directors(
                         id integer not null generated by default as identity (start with 1, increment by 1),
                         name varchar(100) not null unique,
                         director_id integer not null references persons on delete restrict,
                         primary key (id)
);

create table movies(
                       id integer not null generated by default as identity (start with 1, increment by 1),
                       name varchar(100) not null unique,
                       primary key (id)
);

create table movie_actors(
                             movie_id integer not null references movies on delete restrict,
                             actor_id integer not null references actors on delete restrict,
                             primary key (movie_id, actor_id)
);

create table movie_directors(
                                movie_id integer not null references movies on delete restrict,
                                director_id integer not null references directors on delete restrict,
                                primary key (movie_id, director_id)
);